"use client";

import { useState } from "react";
import { 
    Bell, 
    CheckCheck, 
    Clock, 
    MessageSquare, 
    Share2, 
    Sparkles, 
    ShieldCheck, 
    Trash2 
} from "lucide-react";

export default function NotificationsComponent() {
    const [notifications, setNotifications] = useState([
        { id: 1, title: "Post Successfully Published", desc: "Your post 'Top 10 Productivity Tools' was published to LinkedIn.", time: "10 mins ago", read: false, icon: Share2, color: "text-blue-500 bg-blue-50" },
        { id: 2, title: "AI Generation Ready", desc: "Your requested Twitter thread batch has been generated by Creator AI.", time: "1 hour ago", read: false, icon: Sparkles, color: "text-amber-500 bg-amber-50" },
        { id: 3, title: "New Account Connected", desc: "Instagram Business @creatorstack.ui was connected successfully.", time: "Yesterday", read: true, icon: ShieldCheck, color: "text-emerald-500 bg-emerald-50" },
        { id: 4, title: "Weekly Performance Report", desc: "Your total reach increased by 14.2% over the last 7 days.", time: "2 days ago", read: true, icon: Bell, color: "text-purple-500 bg-purple-50" },
    ]);

    const markAllRead = () => {
        setNotifications(notifications.map(n => ({ ...n, read: true })));
    };

    const deleteNotification = (id: number) => {
        setNotifications(notifications.filter(n => n.id !== id));
    };

    return (
        <div className="p-6 max-w-6xl mx-auto space-y-6">
            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 bg-white p-6 rounded-2xl shadow-sm border border-slate-200/80">
                <div>
                    <h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                        <Bell className="w-7 h-7 text-primary" /> Notifications & Alerts
                    </h1>
                    <p className="text-slate-500 text-sm mt-1">Stay updated with your latest post activities and system updates</p>
                </div>
                {notifications.some(n => !n.read) && (
                    <button
                        onClick={markAllRead}
                        className="flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-100 text-slate-700 font-medium text-xs hover:bg-slate-200 transition self-start sm:self-auto"
                    >
                        <CheckCheck className="w-4 h-4 text-emerald-600" />
                        Mark All as Read
                    </button>
                )}
            </div>

            {/* Notification List */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-200/80 divide-y divide-slate-100 overflow-hidden">
                {notifications.length > 0 ? (
                    notifications.map((item) => {
                        const Icon = item.icon;
                        return (
                            <div
                                key={item.id}
                                className={`p-5 flex items-start justify-between gap-4 transition ${
                                    item.read ? "bg-white" : "bg-blue-50/30"
                                }`}
                            >
                                <div className="flex items-start gap-4">
                                    <div className={`p-3 rounded-xl ${item.color}`}>
                                        <Icon className="w-5 h-5" />
                                    </div>
                                    <div className="space-y-1">
                                        <div className="flex items-center gap-2">
                                            <h4 className="text-sm font-bold text-slate-800">{item.title}</h4>
                                            {!item.read && (
                                                <span className="w-2 h-2 rounded-full bg-primary inline-block"></span>
                                            )}
                                        </div>
                                        <p className="text-xs text-slate-600 leading-relaxed">{item.desc}</p>
                                        <span className="text-[11px] text-slate-400 flex items-center gap-1 pt-1">
                                            <Clock className="w-3 h-3" /> {item.time}
                                        </span>
                                    </div>
                                </div>

                                <button
                                    onClick={() => deleteNotification(item.id)}
                                    className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition"
                                >
                                    <Trash2 className="w-4 h-4" />
                                </button>
                            </div>
                        );
                    })
                ) : (
                    <div className="p-12 text-center text-slate-400 space-y-2">
                        <Bell className="w-8 h-8 mx-auto text-slate-300" />
                        <p className="text-sm font-medium">No notifications right now.</p>
                    </div>
                )}
            </div>
        </div>
    );
}
